openapi: 3.1.0
info:
  contact:
    email: chuck.marco@prattwhitney.com
    name: Chuck Marco
    url: https://www.dbds.com
  description: DOME Application RESTful WST (Workscope Tool) API.
  title: Digital Overhaul Management of Engines
  version: 2025-03-24
externalDocs:
  description: Project SharePoint
servers:
- description: DBDS Devlelopment
  url: http://192.168.3.171:81/dome
- description: DBDS Stage
  url: http://192.168.3.171:82/dome
- description: P&W Stage
  url: https://dome-ui-test.prattwhitney.com/dome
security:
- bearerAuth: []
tags:
- description: "MRO (maintenance, repair and operations) Collaboration API."
  name: MRO Collab
paths:
  /v1/workscopetool/pushworkscopedate:
    post:
      operationId: updateWorkscopeFromWST
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WorkscopeRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: OK
      tags:
      - Workscope
components:
  schemas:
    ErrorResponse:
      type: object
      description: Application response schema.
      properties:
        errors:
          type: array
          description: Chain of application error messages.
          items:
            type: string
        message:
          type: string
          description: Application message.
        reason:
          type: string
          description: "The HttpStatus Reason Phrase  (e.g., NOT FOUND)."
        status:
          type: string
          description: "The HttpStatus name (e.g., NOT_FOUND)."
        statusCode:
          type: integer
          format: int32
          description: "The HttpStatus value  (e.g., 404)."
    WorkscopeRequest:
      type: object
      description: Delete work order schema.
      properties:
        esn:
          type: string
        eventId:
          type: integer
          format: int32
        maintenanceId:
          type: integer
          format: int32
          description: many-to-one with serviceTrackerId
        operator:
          type: string
        provider:
          type: string
        serviceTrackerId:
          type: integer
          format: int32
          description: one-to-many with maintenanceId
        smiNumber:
          type: string
        svClassification:
          type: string
        wscreatedBy:
          type: string
        wsinitiationDateTime:
          type: string
          format: date-time
        wspublishedDateTime:
          type: string
          format: date-time
      required:
      - esn
      - maintenanceId
      - operator
      - provider
      - serviceTrackerId
      - smiNumber
      - svClassification
  securitySchemes:
    bearerAuth:
      bearerFormat: jwt
      description: JWT Bearer Authorization.
      scheme: bearer
      type: http
