openapi: 3.1.0
info:
  contact:
    email: chuck.marco@prattwhitney.com
    name: Project manager- Chuck Marco
  description: DOME Application RESTful API for use by Shipping Application.
  title: Digital Overhaul Management of Engines (DOME)
  version: "Version: 2025-07-21"
externalDocs:
  description: Project SharePoint
servers:
- description: DBDS Development
  url: http://192.168.3.171:81/dome
- description: DBDS Stage
  url: http://192.168.3.171:82/dome
- description: P&W Stage
  url: https://dome-ui-test.prattwhitney.com/dome
security:
- bearerAuth: []
tags:
- description: "MRO (Maintenance, Repair and Operations) Collaboration API."
  name: MRO Collab
- description: WST (Workscope Tool) API.
  name: Workscope Tool
paths:
  /v1/external/shipping/dome-shipping-details:
    post:
      description: Updates the matching DOME record with the actual shipping information.
      operationId: updateEngineComments
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ShippingDatesRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"
          description: Subsequent invocation with the same request payload.
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"
          description: Shipping information was updated successfully.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"
          description: The request failed request validation.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"
          description: No DOME records matched the provided engine serial number.
      tags:
      - ShipDates
components:
  schemas:
    ProblemDetail:
      type: object
      properties:
        detail:
          type: string
        instance:
          type: string
          format: uri
        properties:
          type: object
          additionalProperties: {}
        status:
          type: integer
          format: int32
        title:
          type: string
        type:
          type: string
          format: uri
    ShippingDatesRequest:
      type: object
      properties:
        actualArrivalEBUDate:
          type: string
          format: date
          description: The EBU actual arrival date or null if none. ISO 8601 format
            (yyyy-MM-dd) required.
        actualArrivalMaintCenterDate:
          type: string
          format: date
          description: The maintenance center actual arrival date or null if none.  ISO
            8601 format (yyyy-MM-dd) required.
        airwayBill:
          type: string
          description: The airway bill or null if none.
        currentLocation:
          type: string
          description: The current location or null if none.
        engineSerialNumber:
          type: string
          description: The mandatory engine serial number (ESN).
          maxLength: 20
          minLength: 1
        estimatedArrivalEBUDate:
          type: string
          format: date
          description: The EBU estimated time of arrival or null if none. ISO 8601
            format (yyyy-MM-dd) required.
        estimatedArrivalMaintCenterDate:
          type: string
          format: date
          description: The maintenance center estimated time of arrival date or null
            if none. ISO 8601 format (yyyy-MM-dd) required.
        pickupDate:
          type: string
          format: date
          description: The pickup date or null if none. ISO 8601 format (yyyy-MM-dd)
            required.
        shipmentStatus:
          type: string
          description: The shipping status or null if none.
        shippingCompany:
          type: string
          description: The shipping company or null if none.
      required:
      - engineSerialNumber
      title: ShippingDatesRequestModel
  securitySchemes:
    bearerAuth:
      bearerFormat: jwt
      description: JWT Bearer Authorization.
      scheme: bearer
      type: http
