openapi: 3.1.0
info:
  contact:
    email: chuck.marco@prattwhitney.com
    name: Project manager- Chuck Marco
  description: DOME Application RESTful API for shop use.
  title: Digital Overhaul Management of Engines (DOME)
  version: "Version: 2025-09-23"
externalDocs:
  description: Project SharePoint
servers:
- description: DBDS Development
  url: http://192.168.3.171:81/dome
- description: DBDS Stage
  url: http://192.168.3.171:82/dome
- description: P&W Stage
  url: https://dome-ui-test.prattwhitney.com/dome
security:
- bearerAuth: []
tags:
- description: "MRO (Maintenance, Repair and Operations) Collaboration API."
  name: MRO Collab
- description: WST (Workscope Tool) API.
  name: Workscope Tool
paths:
  /v1/external/shop/dome-dates:
    post:
      description: Updates the matching DOME record(s) with the provided non-null
        shop dates. Dates are required to be in ISO 8601 format (yyyy-MM-dd).
      operationId: updateEngineComments
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ShopDatesRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              examples:
                OK:
                  description: OK
                  value: Success
              schema:
                $ref: "#/components/schemas/ProblemDetail"
          description: Successfully updated the matching DOME record.
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Invalid request.
        "404":
          content:
            application/json:
              schema:
                type: string
          description: The matching DOME record was not found.
      tags:
      - ShopDates
components:
  schemas:
    ProblemDetail:
      type: object
      properties:
        detail:
          type: string
        instance:
          type: string
          format: uri
        properties:
          type: object
          additionalProperties: {}
        status:
          type: integer
          format: int32
        title:
          type: string
        type:
          type: string
          format: uri
    ShopDatesRequest:
      type: object
      properties:
        actualAssetCompleteDate:
          type: string
          format: date
          description: The new shop date or null if none.
        actualContractDate:
          type: string
          format: date
          description: The new shop date or null if none.
        actualCoreAssemblyDate:
          type: string
          format: date
          description: The new shop date or null if none.
        actualG1CloseDate:
          type: string
          format: date
          description: The new shop date or null if none.
        actualG3CloseDate:
          type: string
          format: date
          description: The new shop date or null if none.
        actualG3StartDate:
          type: string
          format: date
          description: The new shop date or null if none.
        actualInductDate:
          type: string
          format: date
          description: The new shop date or null if none.
        actualKitCompleteDate:
          type: string
          format: date
          description: The new shop date or null if none.
        actualReceiptDate:
          type: string
          format: date
          description: The new shop date or null if none.
        actualReceiveDate:
          type: string
          format: date
          description: The new shop date or null if none.
        actualShipDate:
          type: string
          format: date
          description: The new shop date or null if none.
        actualShipToCustomerDate:
          type: string
          format: date
        actualTestCompleteDate:
          type: string
          format: date
          description: The new shop date or null if none.
        actualTestStartDate:
          type: string
          format: date
          description: The new shop date or null if none.
        countCmplt:
          type: boolean
          description: AKA warranty.
        countInduct:
          type: boolean
          description: AKA revenue.
        engPassBSI:
          type: boolean
        engPassTest:
          type: boolean
        engineCenter:
          type: string
          description: "The mandatory engine center Id. Example: EC342"
          minLength: 1
        engineCenterName:
          type: string
          description: "The mandatory engine center name. Example: LHT AERO Alzey"
        engineSerialNumber:
          type: string
          description: The mandatory ESN.
          minLength: 1
        planAssetCompleteDate:
          type: string
          format: date
          description: The new planned shop date or null if none.
        planCoreAssemblyDate:
          type: string
          format: date
          description: The new planned shop date or null if none.
        planGate1CloseDate:
          type: string
          format: date
          description: The new planned shop date or null if none.
        planGate3CloseDate:
          type: string
          format: date
          description: The new planned shop date or null if none.
        planGate3StartDate:
          type: string
          format: date
          description: The new planned shop date or null if none.
        planKitCompleteDate:
          type: string
          format: date
          description: The new planned shop date or null if none.
        planReceiptDate:
          type: string
          format: date
          description: The new planned shop date or null if none.
        planReceiveDate:
          type: string
          format: date
          description: The new planned shop date or null if none.
        planShipDate:
          type: string
          format: date
          description: The new planned shop date or null if none.
        planShipToCustomerDate:
          type: string
          format: date
          description: The new shop date or null if none.
        planTestCompleteDate:
          type: string
          format: date
          description: The new planned shop date or null if none.
        planTestStartDate:
          type: string
          format: date
          description: The new planned shop date or null if none.
        salesOrder:
          type: string
        shopVisitNumber:
          type: integer
          format: int32
      required:
      - engineCenter
      - engineSerialNumber
  securitySchemes:
    bearerAuth:
      bearerFormat: jwt
      description: JWT Bearer Authorization.
      scheme: bearer
      type: http
