openapi: 3.1.0
info:
  contact:
    email: chuck.marco@prattwhitney.com
    name: Project manager- Chuck Marco
  description: DOME Application RESTful API for use by Shipping Application.
  title: Digital Overhaul Management of Engines (DOME)
  version: "Version: 2025-07-21"
externalDocs:
  description: Project SharePoint
servers:
- description: DBDS Development
  url: http://192.168.3.171:81/dome
- description: DBDS Stage
  url: http://192.168.3.171:82/dome
- description: P&W Stage
  url: https://dome-ui-test.prattwhitney.com/dome
security:
- bearerAuth: []
tags:
- description: "MRO (Maintenance, Repair and Operations) Collaboration API."
  name: MRO Collab
- description: WST (Workscope Tool) API.
  name: Workscope Tool
paths:
  /v1/external/shipping/dome-shipping-details:
    post:
      description: Updates the matching DOME record with the actual shipping information.
      operationId: updateEngineComments
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ShippingDatesRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseDetails"
          description: Subsequent invocation with the same request payload.
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseDetails"
          description: Shipping information was updated successfully.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"
          description: The request failed request validation.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"
          description: No DOME records matched the provided engine serial number.
      tags:
      - ShipDates
components:
  schemas:
    ProblemDetail:
      type: object
      properties:
        detail:
          type: string
        instance:
          type: string
          format: uri
        properties:
          type: object
          additionalProperties: {}
        status:
          type: integer
          format: int32
        title:
          type: string
        type:
          type: string
          format: uri
    ResponseDetails:
      type: object
      description: foo
      properties:
        detail:
          type: string
        detailAndElapsedTime:
          type: string
          writeOnly: true
        httpStatus:
          type: string
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 EARLY_HINTS
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        instance:
          type: string
          format: uri
        properties:
          type: object
          additionalProperties: {}
        status:
          type: integer
          format: int32
        statusAndElapsedTime:
          type: string
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 EARLY_HINTS
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
          writeOnly: true
        title:
          type: string
        type:
          type: string
          format: uri
    ShippingDatesRequest:
      type: object
      properties:
        actualArrivalEBUDate:
          type: string
          format: date
          description: The EBU actual arrival date or null if none. ISO 8601 format
            (yyyy-MM-dd) required.
        actualArrivalMaintCenterDate:
          type: string
          format: date
          description: The maintenance center actual arrival date or null if none.  ISO
            8601 format (yyyy-MM-dd) required.
        airwayBill:
          type: string
          description: The airway bill or null if none.
        currentLocation:
          type: string
          description: The current location or null if none.
        engineSerialNumber:
          type: string
          description: The mandatory engine serial number (ESN).
          minLength: 1
        estimatedArrivalEBUDate:
          type: string
          format: date
          description: The EBU estimated time of arrival or null if none. ISO 8601
            format (yyyy-MM-dd) required.
        estimatedArrivalMaintCenterDate:
          type: string
          format: date
          description: The maintenance center estimated time of arrival date or null
            if none. ISO 8601 format (yyyy-MM-dd) required.
        pickupDate:
          type: string
          format: date
          description: The pickup date or null if none. ISO 8601 format (yyyy-MM-dd)
            required.
        shipmentStatus:
          type: string
          description: The shipping status or null if none.
        shippingCompany:
          type: string
          description: The shipping company or null if none.
      required:
      - engineSerialNumber
      title: ShippingDatesRequestModel
  securitySchemes:
    bearerAuth:
      bearerFormat: jwt
      description: JWT Bearer Authorization.
      scheme: bearer
      type: http
